// The captured terminal runs and footage clip lengths the composition replays. Both directories are
// produced by capture/term.mjs and capture/footage.mjs and are not committed: they are raw captures,
// regenerated by running those scripts again.
import walkthrough from '../public/captures/walkthrough.json';
import forgeTest from '../public/captures/forge-test.json';
import testBand from '../public/captures/test-band.json';
import ensResolve from '../public/captures/ens-resolve.json';
import ensVerify from '../public/captures/ens-verify.json';
import counterpartyParanoid from '../public/captures/counterparty-paranoid.json';
import a2a from '../public/captures/a2a.json';
import htsPay from '../public/captures/hts-pay.json';
import paymentsAfter from '../public/captures/payments-after.json';
import subscribeStatus from '../public/captures/subscribe-status.json';
import holFind from '../public/captures/hol-find.json';
import agentKit from '../public/captures/agent-kit.json';
import commits from '../public/captures/commits.json';

import hero from '../public/footage/hero.json';
import app from '../public/footage/app.json';
import ship from '../public/footage/ship.json';
import swap from '../public/footage/swap.json';
import register from '../public/footage/register.json';
import registry from '../public/footage/registry.json';
import grant from '../public/footage/grant.json';
import textwrite from '../public/footage/textwrite.json';
import resolver from '../public/footage/resolver.json';
import alias from '../public/footage/alias.json';
import uri from '../public/footage/uri.json';
import aqua from '../public/footage/aqua.json';
import token from '../public/footage/token.json';
import schedule from '../public/footage/schedule.json';
import mirror from '../public/footage/mirror.json';
import name from '../public/footage/name.json';
import x402 from '../public/footage/x402.json';
import card from '../public/footage/card.json';
import killswitch from '../public/footage/killswitch.json';
import readme from '../public/footage/readme.json';

export const CAPTURES = {
    walkthrough, 'forge-test': forgeTest, 'test-band': testBand, 'ens-resolve': ensResolve, 'ens-verify': ensVerify,
    'counterparty-paranoid': counterpartyParanoid, a2a, 'hts-pay': htsPay, 'payments-after': paymentsAfter,
    'subscribe-status': subscribeStatus, 'hol-find': holFind, 'agent-kit': agentKit, commits,
};

// Seconds of usable video per clip; a shot that runs past it holds the last frame instead of going black.
export const CLIP_SECONDS = Object.fromEntries(
    [hero, app, ship, swap, register, registry, grant, textwrite, resolver, alias, uri, aqua, token, schedule, mirror, name, x402, card, killswitch, readme]
        .map((c) => [c.name, c.durationMs / 1000 - 0.6]),
);
